#!/usr/bin/env node
// Model Context Protocol (MCP) server for Qbort.
// Exposes tools, resources, and prompts for fake customer support ticket generation and inspection.
// Compatible with any MCP client (Claude Desktop, Cursor, Windsurf, Claude Code, Antigravity, etc.).
//
// Zero-dependency ESM on bare node (20+), strictly matching qbort's architecture.

import { readdirSync, statSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { createInterface } from 'node:readline'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { parseArgs } from '../lib/args.mjs'
import { DEFAULT_BATCH_SIZE } from '../lib/constants.mjs'
import { atomicWriteJson, atomicWriteText, readJson, readText } from '../lib/fsUtil.mjs'
import { OUTPUT_DIR, OUTPUT_FILE_RE, SCRATCH_DIR, outputFileName } from '../lib/paths.mjs'
import { buildRound, shuffled } from '../lib/pipeline.mjs'
import { compilePromptParts, compileScenarioPrompt, scenarioTarget } from '../lib/promptCompiler.mjs'
import { clearScratch } from '../lib/scratch.mjs'
import { clampGeneration } from '../lib/settings.mjs'
import { generateRoster } from '../lib/staff.mjs'
import { parseTicketFile } from '../lib/ticketFile.mjs'
import { openingTimesForRun } from '../lib/time.mjs'
import { assembleTickets, validateTickets } from '../lib/validate.mjs'
import { pluginVersion } from '../lib/version.mjs'
import { newestOutputPath, parseIdSpec, selectTickets, summarize } from '../lib/viewer.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const STARTER_TEMPLATE_PATH = resolve(__dirname, '../skills/generate-tickets/templates/TICKET_PROMPT.md')

/**
 * Tool definitions exposed by the Qbort MCP server.
 */
export const MCP_TOOLS = [
  {
    name: 'scaffold_ticket_prompt',
    description:
      'Scaffold a starter TICKET_PROMPT.md file in the target directory (defaults to current working directory) if one does not already exist. Returns the template content and status.',
    inputSchema: {
      type: 'object',
      properties: {
        targetDir: {
          type: 'string',
          description: 'Directory where TICKET_PROMPT.md should be created (default: .)'
        },
        overwrite: {
          type: 'boolean',
          description: 'Whether to overwrite an existing TICKET_PROMPT.md file (default: false)'
        }
      }
    }
  },
  {
    name: 'plan_ticket_run',
    description:
      'Plan a ticket generation run. Clears the scratch directory (.qbort-run), clamps settings to valid bounds, creates the staff roster, generates opening timestamps, and compiles the scenario prompt. Returns the scenario prompt that the model should use to generate scenarios.',
    inputSchema: {
      type: 'object',
      properties: {
        promptFile: {
          type: 'string',
          description: 'Path to prompt markdown file (default: TICKET_PROMPT.md relative to workingDir)'
        },
        promptText: {
          type: 'string',
          description: 'Optional inline prompt markdown text to use instead of reading promptFile'
        },
        count: {
          type: 'number',
          description: 'Number of tickets to generate, 1 to 500 (default: 100)'
        },
        includeStaffResponses: {
          type: 'boolean',
          description: 'Whether to include staff responses in tickets (default: false)'
        },
        avgStaffResponses: {
          type: 'number',
          description: 'Average staff replies per ticket when staff responses are enabled, 0 to 20 (default: 0)'
        },
        numStaffMembers: {
          type: 'number',
          description: 'Number of staff members on the support roster, 1 to 100 (default: 10)'
        },
        maxTicketAgeDays: {
          type: 'number',
          description: 'How far back ticket open times are spread in days, 1 to 3650 (default: 90)'
        },
        batchSize: {
          type: 'number',
          description: 'Number of tickets per generation batch (default: 20)'
        },
        workingDir: {
          type: 'string',
          description: 'Working directory containing .qbort-run scratch and qbort-output product (default: .)'
        }
      }
    }
  },
  {
    name: 'build_ticket_batches',
    description:
      'Validates and shuffles the scenario list, deals one scenario per ticket, and compiles per-batch prompts. Scenarios can be passed directly as an array or read from .qbort-run/scenarios.json. Returns batch definitions with their prompt text and target paths.',
    inputSchema: {
      type: 'object',
      properties: {
        scenarios: {
          type: 'array',
          items: { type: 'string' },
          description: 'List of one-line ticket scenarios generated by the model'
        },
        workingDir: {
          type: 'string',
          description: 'Working directory containing .qbort-run (default: .)'
        }
      }
    }
  },
  {
    name: 'assemble_tickets',
    description:
      'Validates and repairs batch ticket outputs, assigns sequential IDs, staff roles, and synthesized timestamps, caps to requested counts, and writes or updates the timestamped tickets.json in qbort-output/. Batches can be read from disk or supplied directly in arguments.',
    inputSchema: {
      type: 'object',
      properties: {
        round: {
          type: 'number',
          description: 'Generation round number to assemble (default: 0)'
        },
        batches: {
          type: 'array',
          description: 'Optional array of batch outputs ({ index: number, tickets?: Ticket[], rawJson?: string }) to assemble directly without reading disk',
          items: {
            type: 'object',
            properties: {
              index: { type: 'number' },
              rawJson: { type: 'string' },
              tickets: { type: 'array', items: { type: 'object' } }
            },
            required: ['index']
          }
        },
        workingDir: {
          type: 'string',
          description: 'Working directory containing .qbort-run and qbort-output (default: .)'
        }
      }
    }
  },
  {
    name: 'prepare_topup',
    description:
      'Prepares a top-up round to make up any shortfall from validation drops. Draws fresh scenarios from the reserve and compiles top-up batch prompts. Returns batch definitions for the top-up round.',
    inputSchema: {
      type: 'object',
      properties: {
        round: {
          type: 'number',
          description: 'Top-up round number, 1 to 3'
        },
        workingDir: {
          type: 'string',
          description: 'Working directory containing .qbort-run (default: .)'
        }
      },
      required: ['round']
    }
  },
  {
    name: 'list_ticket_runs',
    description:
      'List all generated ticket files in qbort-output/, sorted newest first, with summary metadata (date, requested/generated counts, provider/model, file size).',
    inputSchema: {
      type: 'object',
      properties: {
        workingDir: {
          type: 'string',
          description: 'Directory containing qbort-output (default: .)'
        }
      }
    }
  },
  {
    name: 'get_run_stats',
    description:
      'Get statistical metrics for a generated tickets.json file: ticket count, breakdown by status, message totals, staff reply rates, unanswered count, and date span.',
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'Path to tickets file (default: newest file in qbort-output/)'
        },
        workingDir: {
          type: 'string',
          description: 'Directory containing qbort-output (default: .)'
        }
      }
    }
  },
  {
    name: 'view_tickets',
    description:
      'Search, filter, and paginate tickets from a generated tickets file. Supports filtering by ID range, status, keyword search across subjects and message bodies, and thread expansion.',
    inputSchema: {
      type: 'object',
      properties: {
        file: {
          type: 'string',
          description: 'Path to tickets file (default: newest in qbort-output/)'
        },
        id: {
          type: 'string',
          description: "Specific IDs or ranges: '7', '3,9', '10-20'"
        },
        status: {
          type: 'string',
          description: "Comma-separated statuses: 'new,open,solved'"
        },
        search: {
          type: 'string',
          description: 'Keyword search in subjects and message bodies'
        },
        full: {
          type: 'boolean',
          description: 'Return full message threads instead of summary headers (default: false)'
        },
        limit: {
          type: 'number',
          description: 'Tickets per page (default: 50 for summary, 5 for full threads; 0 for all)'
        },
        page: {
          type: 'number',
          description: '1-based page number (default: 1)'
        },
        workingDir: {
          type: 'string',
          description: 'Directory containing qbort-output (default: .)'
        }
      }
    }
  },
  {
    name: 'get_ticket',
    description: 'Retrieve the full message thread and details for a single ticket by its integer ID.',
    inputSchema: {
      type: 'object',
      properties: {
        id: {
          type: 'number',
          description: 'Ticket ID to retrieve'
        },
        file: {
          type: 'string',
          description: 'Path to tickets file (default: newest in qbort-output/)'
        },
        workingDir: {
          type: 'string',
          description: 'Directory containing qbort-output (default: .)'
        }
      },
      required: ['id']
    }
  }
]

/**
 * Resource definitions exposed by the Qbort MCP server.
 */
export const MCP_RESOURCES = [
  {
    uri: 'qbort://template/ticket-prompt',
    name: 'Ticket Prompt Template',
    description: 'Starter markdown template for TICKET_PROMPT.md to shape customer support ticket scenarios',
    mimeType: 'text/markdown'
  },
  {
    uri: 'qbort://runs/latest',
    name: 'Latest Ticket Run Output',
    description: 'Full JSON output of the newest generated tickets file in qbort-output/',
    mimeType: 'application/json'
  },
  {
    uri: 'qbort://runs/latest/stats',
    name: 'Latest Ticket Run Statistics',
    description: 'Statistical breakdown and status distributions of the newest generated tickets file',
    mimeType: 'application/json'
  }
]

/**
 * Prompt templates exposed by the Qbort MCP server.
 */
export const MCP_PROMPTS = [
  {
    name: 'generate-tickets',
    description: 'Guided prompt to plan and generate realistic synthetic customer support tickets with Qbort',
    arguments: [
      {
        name: 'product',
        description: 'Description of the product or service being modeled',
        required: false
      },
      {
        name: 'count',
        description: 'Number of tickets to generate (1-500, default: 50)',
        required: false
      },
      {
        name: 'includeStaff',
        description: 'Whether to include staff replies (default: true)',
        required: false
      }
    ]
  },
  {
    name: 'review-tickets',
    description: 'Prompt to analyze and critique the latest generated ticket dataset for quality and realism',
    arguments: [
      {
        name: 'focus',
        description: 'Specific focus area (e.g., tone, sentiment, edge cases, category balance)',
        required: false
      }
    ]
  }
]

/**
 * Creates an instance of the Qbort MCP server.
 * @param {{ defaultWorkingDir?: string }} [options]
 */
export function createMcpServer(options = {}) {
  const defaultDir = options.defaultWorkingDir || process.cwd()

  function getBaseDir(args) {
    return resolve(args?.workingDir || defaultDir)
  }

  // ── Tool execution handlers ─────────────────────────────────────────────────

  async function toolScaffoldTicketPrompt(args = {}) {
    const targetDir = resolve(args.targetDir || defaultDir)
    const targetPath = join(targetDir, 'TICKET_PROMPT.md')
    const templateText = await readText(STARTER_TEMPLATE_PATH)
    if (!templateText) {
      throw new Error(`Starter template not found at ${STARTER_TEMPLATE_PATH}`)
    }

    const existing = await readText(targetPath)
    if (existing !== null && !args.overwrite) {
      return {
        created: false,
        message: `TICKET_PROMPT.md already exists at ${targetPath}. Set overwrite=true to replace it.`,
        path: targetPath,
        content: existing
      }
    }

    await atomicWriteText(targetPath, templateText)
    return {
      created: true,
      message: `Scaffolded starter TICKET_PROMPT.md at ${targetPath}. Edit this file to describe your product and ticket distribution.`,
      path: targetPath,
      content: templateText
    }
  }

  async function toolPlanTicketRun(args = {}) {
    const baseDir = getBaseDir(args)
    const scratchDir = join(baseDir, SCRATCH_DIR)
    const outputDir = join(baseDir, OUTPUT_DIR)

    await clearScratch(scratchDir)

    let prompt = args.promptText
    let promptPath = null
    if (typeof prompt !== 'string' || !prompt.trim()) {
      promptPath = resolve(baseDir, args.promptFile || 'TICKET_PROMPT.md')
      prompt = await readText(promptPath)
      if (prompt === null) {
        throw new Error(
          `Missing prompt file at ${promptPath}. Call scaffold_ticket_prompt first or supply promptText.`
        )
      }
    }

    const settings = clampGeneration({
      numTickets: args.count !== undefined ? Number(args.count) : undefined,
      includeStaffResponses: Boolean(args.includeStaffResponses),
      avgStaffResponses: args.avgStaffResponses !== undefined ? Number(args.avgStaffResponses) : undefined,
      numStaffMembers: args.numStaffMembers !== undefined ? Number(args.numStaffMembers) : undefined,
      maxTicketAgeDays: args.maxTicketAgeDays !== undefined ? Number(args.maxTicketAgeDays) : undefined
    })

    const nowMs = Date.now()
    const batchSize =
      args.batchSize !== undefined ? Math.max(1, Number(args.batchSize)) : DEFAULT_BATCH_SIZE

    const roster = generateRoster(settings.numStaffMembers)
    const openingTimes = openingTimesForRun(settings.numTickets, settings.maxTicketAgeDays, nowMs)

    const { static: staticPrefix } = compilePromptParts({
      editablePrompt: prompt,
      batchCount: 0,
      staff: {
        include: settings.includeStaffResponses,
        avgResponses: settings.avgStaffResponses,
        roster,
        responseCounts: settings.includeStaffResponses ? [] : undefined
      }
    })

    const outputFile = outputFileName(new Date(nowMs))
    const scenarioCount = scenarioTarget(settings.numTickets)

    const ctx = {
      version: 1,
      nowMs,
      outputFile,
      batchSize,
      prompt,
      settings,
      roster,
      staticPrefix,
      openingTimes,
      round: 0,
      generatedCount: 0,
      dropped: 0,
      scenarioCount,
      scenarios: [],
      scenarioCursor: 0,
      tickets: []
    }

    await atomicWriteJson(join(scratchDir, 'run-context.json'), ctx)

    const scenarioPromptText = compileScenarioPrompt(prompt, scenarioCount)
    const scenarioPromptFile = join(scratchDir, 'scenario-prompt.txt')
    const scenariosFile = join(scratchDir, 'scenarios.json')
    await atomicWriteText(scenarioPromptFile, `${scenarioPromptText}\n`)

    return {
      plannedTickets: settings.numTickets,
      batchSize,
      staffResponses: settings.includeStaffResponses,
      staffRosterSize: roster.length,
      scratchDir,
      outputFile: join(outputDir, outputFile),
      scenarioCount,
      scenarioPromptFile,
      scenariosFile,
      scenarioPrompt: scenarioPromptText,
      instructions:
        `1. Generate exactly ${scenarioCount} one-line ticket scenarios following the instructions in scenarioPrompt.\n` +
        '2. Call build_ticket_batches with your scenario array or write them to scenarios.json.'
    }
  }

  async function toolBuildTicketBatches(args = {}) {
    const baseDir = getBaseDir(args)
    const scratchDir = join(baseDir, SCRATCH_DIR)
    const ctx = await readJson(join(scratchDir, 'run-context.json'))
    if (!ctx) {
      throw new Error('NO_CONTEXT: Run plan_ticket_run first before building batches.')
    }

    const scenariosPath = join(scratchDir, 'scenarios.json')
    if (Array.isArray(args.scenarios)) {
      await atomicWriteJson(scenariosPath, { scenarios: args.scenarios })
    }

    const raw = await readText(scenariosPath)
    if (raw === null) {
      throw new Error(`NO_SCENARIOS: ${scenariosPath} not found. Provide scenarios in arguments or write the file.`)
    }

    let parsed = null
    try {
      parsed = JSON.parse(raw)
    } catch {
      const start = raw.indexOf('{')
      const end = raw.lastIndexOf('}')
      if (start !== -1 && end > start) {
        try {
          parsed = JSON.parse(raw.slice(start, end + 1))
        } catch {
          /* lenient parse fallback */
        }
      }
    }

    const list = Array.isArray(parsed) ? parsed : parsed?.scenarios
    if (!Array.isArray(list)) {
      throw new Error(`BAD_SCENARIOS: ${scenariosPath} is not a valid JSON array or object with a scenarios list.`)
    }

    const cleaned = list.filter((s) => typeof s === 'string' && s.trim().length > 0).map((s) => s.trim())
    const needed = ctx.settings.numTickets
    if (cleaned.length < needed) {
      throw new Error(
        `SHORT_SCENARIOS: Got ${cleaned.length} usable scenarios, need at least ${needed} (asked for ${ctx.scenarioCount}).`
      )
    }

    ctx.scenarios = shuffled(cleaned)
    ctx.scenarioCursor = 0
    const manifest = await buildRound(ctx, 0, needed, scratchDir)
    await atomicWriteJson(join(scratchDir, 'run-context.json'), ctx)

    return {
      round: 0,
      totalScenarios: ctx.scenarios.length,
      reserveScenarios: ctx.scenarios.length - needed,
      batches: manifest.batches,
      instructions:
        'Generate tickets for each batch according to its promptText or promptFile. ' +
        'Either write the resulting JSON array of tickets to each batchFile or call assemble_tickets with batches array.'
    }
  }

  async function toolAssembleTickets(args = {}) {
    const baseDir = getBaseDir(args)
    const scratchDir = join(baseDir, SCRATCH_DIR)
    const outputDir = join(baseDir, OUTPUT_DIR)

    const ctx = await readJson(join(scratchDir, 'run-context.json'))
    if (!ctx) {
      throw new Error('NO_CONTEXT: Run plan_ticket_run first.')
    }

    const round = Number(args.round ?? 0)
    const manifest = await readJson(join(scratchDir, `round-${round}.json`))
    if (!manifest) {
      throw new Error(`NO_ROUND: round-${round}.json not found. Run build_ticket_batches or prepare_topup first.`)
    }

    const total = ctx.settings.numTickets
    const includeStaffResponses = ctx.settings.includeStaffResponses
    const kept = ctx.tickets || []
    const timeCtx = {
      nowMs: ctx.nowMs,
      rng: Math.random,
      openingMsForId: (id) => ctx.openingTimes[id - 1] ?? ctx.nowMs
    }

    const memoryBatches = new Map()
    if (Array.isArray(args.batches)) {
      for (const item of args.batches) {
        if (item && typeof item.index === 'number') {
          memoryBatches.set(item.index, item)
        }
      }
    }

    let roundKept = 0
    for (const b of manifest.batches) {
      if (kept.length >= total) break
      let raw = null
      const inMem = memoryBatches.get(b.index)
      if (inMem) {
        raw = inMem.rawJson || (inMem.tickets ? JSON.stringify(inMem.tickets) : null)
      }
      if (raw === null) {
        raw = await readText(b.batchFile)
      }

      const validated = validateTickets(raw, { includeStaffResponses })
      ctx.dropped = (ctx.dropped || 0) + validated.dropped
      const room = Math.min(b.count, total - kept.length)
      const capped = validated.tickets.slice(0, room)
      const assigned = assembleTickets(capped, kept.length + 1, timeCtx)
      kept.push(...assigned)
      roundKept += assigned.length
    }

    ctx.tickets = kept
    ctx.generatedCount = kept.length
    await atomicWriteJson(join(scratchDir, 'run-context.json'), ctx)

    const ticketsPath = join(outputDir, ctx.outputFile)
    const versionStr = await pluginVersion()
    const file = {
      meta: {
        generatedAt: new Date(ctx.nowMs).toISOString(),
        appVersion: versionStr,
        provider: 'mcp-server',
        model: 'mcp-agent',
        requestedCount: total,
        generatedCount: kept.length,
        settings: { generation: ctx.settings },
        generator: 'qbort-mcp',
        rounds: round + 1,
        dropped: ctx.dropped
      },
      tickets: kept
    }

    if (!parseTicketFile(file)) {
      throw new Error('BAD_OUTPUT: Assembled ticket file does not match tickets.json schema. Nothing was written.')
    }

    await atomicWriteJson(ticketsPath, file)
    const shortfall = total - kept.length

    return {
      round,
      roundKept,
      keptCount: kept.length,
      requestedCount: total,
      droppedCount: ctx.dropped,
      shortfall,
      isComplete: shortfall === 0,
      outputFile: ticketsPath,
      instructions:
        shortfall > 0
          ? `Shortfall of ${shortfall} ticket(s). Call prepare_topup(round: ${round + 1}) to build top-up batches.`
          : `Run complete! Wrote ${kept.length} tickets to ${ticketsPath}. Use view_tickets or get_run_stats to inspect.`
    }
  }

  async function toolPrepareTopup(args = {}) {
    const baseDir = getBaseDir(args)
    const scratchDir = join(baseDir, SCRATCH_DIR)

    const ctx = await readJson(join(scratchDir, 'run-context.json'))
    if (!ctx) {
      throw new Error('NO_CONTEXT: Run plan_ticket_run first.')
    }

    const round = Number(args.round)
    if (!Number.isInteger(round) || round < 1) {
      throw new Error('BAD_ROUND: Topup requires integer round >= 1.')
    }

    const shortfall = ctx.settings.numTickets - ctx.generatedCount
    if (shortfall <= 0) {
      return {
        round,
        shortfall: 0,
        isComplete: true,
        message: 'No shortfall remaining; run is already complete.'
      }
    }

    ctx.round = round
    const reserve = Math.max(0, (ctx.scenarios?.length ?? 0) - ctx.scenarioCursor)
    const manifest = await buildRound(ctx, round, shortfall, scratchDir)
    await atomicWriteJson(join(scratchDir, 'run-context.json'), ctx)

    return {
      round,
      shortfall,
      scenariosAvailableFromReserve: Math.min(reserve, shortfall),
      batches: manifest.batches,
      instructions:
        `Topup round ${round} prepared for ${shortfall} tickets across ${manifest.batches.length} batch(es). ` +
        'Generate tickets for each batch and call assemble_tickets.'
    }
  }

  async function toolListTicketRuns(args = {}) {
    const baseDir = getBaseDir(args)
    const outputDir = join(baseDir, OUTPUT_DIR)

    let names = []
    try {
      names = readdirSync(outputDir)
    } catch {
      return { runs: [], count: 0, outputDir }
    }

    const runFiles = names.filter((n) => OUTPUT_FILE_RE.test(n)).sort().reverse()
    const runs = []
    for (const name of runFiles) {
      const filePath = join(outputDir, name)
      try {
        const stats = statSync(filePath)
        const content = await readJson(filePath)
        runs.push({
          fileName: name,
          filePath,
          generatedAt: content?.meta?.generatedAt || stats.mtime.toISOString(),
          requestedCount: content?.meta?.requestedCount ?? null,
          generatedCount: content?.meta?.generatedCount ?? content?.tickets?.length ?? null,
          provider: content?.meta?.provider ?? null,
          model: content?.meta?.model ?? null,
          rounds: content?.meta?.rounds ?? null,
          fileSizeBytes: stats.size
        })
      } catch {
        /* skip corrupted/unreadable entry */
      }
    }

    return {
      runs,
      count: runs.length,
      outputDir
    }
  }

  async function toolGetRunStats(args = {}) {
    const baseDir = getBaseDir(args)
    const outputDir = join(baseDir, OUTPUT_DIR)
    const filePath = args.file ? resolve(baseDir, args.file) : newestOutputPath(outputDir)

    if (!filePath) {
      throw new Error(`No ticket runs found in ${outputDir}. Pass a file path or generate a run first.`)
    }

    const raw = await readJson(filePath)
    if (!raw) {
      throw new Error(`Could not read ticket file at ${filePath}.`)
    }
    const file = parseTicketFile(raw)
    if (!file) {
      throw new Error(`File at ${filePath} is not a valid qbort tickets.json file.`)
    }

    const stats = summarize(file.tickets)
    return {
      filePath,
      meta: file.meta,
      stats: {
        totalTickets: stats.count,
        byStatus: stats.byStatus,
        totalMessages: stats.messages,
        staffReplies: stats.staffReplies,
        unansweredTickets: stats.unanswered,
        avgMessagesPerTicket: Number(stats.avgMessages.toFixed(2)),
        avgStaffRepliesPerTicket: Number(stats.avgStaffReplies.toFixed(2)),
        dateRange: {
          earliest: stats.earliest,
          latest: stats.latest
        }
      }
    }
  }

  async function toolViewTickets(args = {}) {
    const baseDir = getBaseDir(args)
    const outputDir = join(baseDir, OUTPUT_DIR)
    const filePath = args.file ? resolve(baseDir, args.file) : newestOutputPath(outputDir)

    if (!filePath) {
      throw new Error(`No ticket runs found in ${outputDir}. Pass a file path or generate a run first.`)
    }

    const raw = await readJson(filePath)
    if (!raw) {
      throw new Error(`Could not read ticket file at ${filePath}.`)
    }
    const file = parseTicketFile(raw)
    if (!file) {
      throw new Error(`File at ${filePath} is not a valid qbort tickets.json file.`)
    }

    const ids = typeof args.id === 'string' ? parseIdSpec(args.id) : null
    if (typeof args.id === 'string' && !ids) {
      throw new Error(`Could not parse --id "${args.id}". Use '7', '3,9', or '10-20'.`)
    }

    const statuses =
      typeof args.status === 'string'
        ? new Set(
            args.status
              .split(',')
              .map((s) => s.trim().toLowerCase())
              .filter(Boolean)
          )
        : null

    const search = typeof args.search === 'string' ? args.search : null
    const selected = selectTickets(file.tickets, { ids, statuses, search })

    const full = Boolean(args.full) || Boolean(ids)
    const limit = args.limit !== undefined ? Number(args.limit) : ids ? 0 : full ? 5 : 50
    const page = args.page !== undefined ? Number(args.page) : 1
    const perPage = limit === 0 ? selected.length : Math.max(1, limit)
    const totalPages = Math.max(1, Math.ceil(selected.length / perPage))
    const start = (page - 1) * perPage
    const shown = selected.slice(start, start + perPage)

    const formattedTickets = full
      ? shown
      : shown.map((t) => {
          const staffReplies = t.messages.filter((m) => m.isStaff).length
          const opener = t.messages[0]
          return {
            id: t.id,
            subject: t.subject,
            status: t.status,
            messageCount: t.messages.length,
            staffReplies,
            createdAt: opener?.createdAt,
            opener: opener?.from
          }
        })

    return {
      filePath,
      totalMatched: selected.length,
      totalInFile: file.tickets.length,
      page,
      totalPages,
      limit: perPage,
      fullThreads: full,
      tickets: formattedTickets
    }
  }

  async function toolGetTicket(args = {}) {
    const baseDir = getBaseDir(args)
    const outputDir = join(baseDir, OUTPUT_DIR)
    const filePath = args.file ? resolve(baseDir, args.file) : newestOutputPath(outputDir)

    if (!filePath) {
      throw new Error(`No ticket runs found in ${outputDir}. Pass a file path or generate a run first.`)
    }

    if (args.id === undefined || args.id === null) {
      throw new Error("Missing required argument: 'id'")
    }
    const ticketId = Number(args.id)

    const raw = await readJson(filePath)
    if (!raw) {
      throw new Error(`Could not read ticket file at ${filePath}.`)
    }
    const file = parseTicketFile(raw)
    if (!file) {
      throw new Error(`File at ${filePath} is not a valid qbort tickets.json file.`)
    }

    const ticket = file.tickets.find((t) => t.id === ticketId)
    if (!ticket) {
      throw new Error(`Ticket #${ticketId} not found in ${filePath} (file has ${file.tickets.length} tickets).`)
    }

    return {
      filePath,
      ticket
    }
  }

  // ── Dispatch table ──────────────────────────────────────────────────────────

  const toolHandlers = {
    scaffold_ticket_prompt: toolScaffoldTicketPrompt,
    plan_ticket_run: toolPlanTicketRun,
    build_ticket_batches: toolBuildTicketBatches,
    assemble_tickets: toolAssembleTickets,
    prepare_topup: toolPrepareTopup,
    list_ticket_runs: toolListTicketRuns,
    get_run_stats: toolGetRunStats,
    view_tickets: toolViewTickets,
    get_ticket: toolGetTicket
  }

  /**
   * Call a tool by name with arguments.
   * @param {string} name
   * @param {any} args
   */
  async function callTool(name, args) {
    const handler = toolHandlers[name]
    if (!handler) {
      return {
        content: [{ type: 'text', text: `Unknown tool: ${name}` }],
        isError: true
      }
    }
    try {
      const result = await handler(args || {})
      return {
        content: [
          {
            type: 'text',
            text: typeof result === 'string' ? result : JSON.stringify(result, null, 2)
          }
        ],
        isError: false
      }
    } catch (err) {
      return {
        content: [{ type: 'text', text: String(err?.message || err) }],
        isError: true
      }
    }
  }

  /**
   * Read an MCP resource by URI.
   * @param {string} uri
   */
  async function readResource(uri) {
    if (uri === 'qbort://template/ticket-prompt') {
      const template = await readText(STARTER_TEMPLATE_PATH)
      return {
        contents: [
          {
            uri,
            mimeType: 'text/markdown',
            text: template || ''
          }
        ]
      }
    }

    if (uri === 'qbort://runs/latest') {
      const filePath = newestOutputPath(join(defaultDir, OUTPUT_DIR))
      if (!filePath) {
        throw new Error(`No runs found in ${join(defaultDir, OUTPUT_DIR)}`)
      }
      const raw = await readText(filePath)
      return {
        contents: [
          {
            uri,
            mimeType: 'application/json',
            text: raw || '{}'
          }
        ]
      }
    }

    if (uri === 'qbort://runs/latest/stats') {
      const stats = await toolGetRunStats({ workingDir: defaultDir })
      return {
        contents: [
          {
            uri,
            mimeType: 'application/json',
            text: JSON.stringify(stats, null, 2)
          }
        ]
      }
    }

    throw new Error(`Resource not found: ${uri}`)
  }

  /**
   * Get an MCP prompt definition and messages.
   * @param {string} name
   * @param {any} [args]
   */
  async function getPrompt(name, args = {}) {
    if (name === 'generate-tickets') {
      const product = args.product || 'a modern web application'
      const count = args.count || '50'
      const includeStaff = args.includeStaff !== 'false'
      return {
        description: 'Guided instructions to generate customer support tickets using Qbort tools',
        messages: [
          {
            role: 'user',
            content: {
              type: 'text',
              text:
                `I would like to generate ${count} realistic customer support tickets for ${product}.\n` +
                `Staff replies enabled: ${includeStaff}.\n\n` +
                'Please orchestrate this using the Qbort MCP tools:\n' +
                `1. Call plan_ticket_run(count: ${count}, includeStaffResponses: ${includeStaff})\n` +
                '2. Generate the requested scenario list from the scenario prompt and call build_ticket_batches\n' +
                '3. Generate ticket content for each batch and call assemble_tickets\n' +
                '4. If there is any shortfall, call prepare_topup and assemble the topup batches\n' +
                '5. Summarize the completed run using get_run_stats'
            }
          }
        ]
      }
    }

    if (name === 'review-tickets') {
      const focus = args.focus ? ` Focusing especially on ${args.focus}.` : ''
      return {
        description: 'Guided instructions to review the newest generated ticket dataset',
        messages: [
          {
            role: 'user',
            content: {
              type: 'text',
              text:
                `Please review the latest generated support tickets in qbort-output/.${focus}\n\n` +
                '1. Use get_run_stats to inspect overall metrics, statuses, and message counts.\n' +
                '2. Use view_tickets to sample conversations across different categories.\n' +
                '3. Highlight strengths, realistic elements, and any potential repetitive patterns or areas to improve in the prompt.'
            }
          }
        ]
      }
    }

    throw new Error(`Prompt not found: ${name}`)
  }

  /**
   * Handle an incoming JSON-RPC 2.0 message string or object.
   * Returns a JSON-RPC response object, or null for notifications.
   * @param {string | Record<string, any>} rawMessage
   */
  async function handleMessage(rawMessage) {
    let msg
    if (typeof rawMessage === 'string') {
      try {
        msg = JSON.parse(rawMessage)
      } catch {
        return {
          jsonrpc: '2.0',
          id: null,
          error: { code: -32700, message: 'Parse error' }
        }
      }
    } else {
      msg = rawMessage
    }

    if (!msg || typeof msg !== 'object') {
      return {
        jsonrpc: '2.0',
        id: null,
        error: { code: -32600, message: 'Invalid Request' }
      }
    }

    const { id, method, params } = msg
    const isNotification = id === undefined || id === null

    try {
      switch (method) {
        case 'initialize': {
          const versionStr = await pluginVersion()
          return {
            jsonrpc: '2.0',
            id,
            result: {
              protocolVersion: '2024-11-05',
              capabilities: {
                tools: { listChanged: false },
                resources: { listChanged: false, subscribe: false },
                prompts: { listChanged: false }
              },
              serverInfo: {
                name: 'qbort-mcp',
                version: versionStr
              },
              instructions:
                'Qbort MCP server for synthetic customer support ticket generation and inspection. ' +
                'Use plan_ticket_run, build_ticket_batches, and assemble_tickets to generate datasets. ' +
                'Use list_ticket_runs, get_run_stats, and view_tickets to inspect output.'
            }
          }
        }
        case 'notifications/initialized': {
          return null
        }
        case 'ping': {
          return { jsonrpc: '2.0', id, result: {} }
        }
        case 'tools/list': {
          return {
            jsonrpc: '2.0',
            id,
            result: { tools: MCP_TOOLS }
          }
        }
        case 'tools/call': {
          const toolName = params?.name
          const toolArgs = params?.arguments || {}
          const toolResult = await callTool(toolName, toolArgs)
          return {
            jsonrpc: '2.0',
            id,
            result: toolResult
          }
        }
        case 'resources/list': {
          return {
            jsonrpc: '2.0',
            id,
            result: { resources: MCP_RESOURCES }
          }
        }
        case 'resources/read': {
          const resResult = await readResource(params?.uri)
          return {
            jsonrpc: '2.0',
            id,
            result: resResult
          }
        }
        case 'prompts/list': {
          return {
            jsonrpc: '2.0',
            id,
            result: { prompts: MCP_PROMPTS }
          }
        }
        case 'prompts/get': {
          const promptResult = await getPrompt(params?.name, params?.arguments)
          return {
            jsonrpc: '2.0',
            id,
            result: promptResult
          }
        }
        default: {
          if (isNotification) return null
          return {
            jsonrpc: '2.0',
            id,
            error: { code: -32601, message: `Method not found: ${method}` }
          }
        }
      }
    } catch (err) {
      if (isNotification) return null
      return {
        jsonrpc: '2.0',
        id,
        error: { code: -32603, message: String(err?.message || err) }
      }
    }
  }

  /**
   * Start the stdio JSON-RPC loop.
   * @param {NodeJS.ReadableStream} [inStream]
   * @param {NodeJS.WritableStream} [outStream]
   */
  function start(inStream = process.stdin, outStream = process.stdout) {
    const rl = createInterface({
      input: inStream,
      terminal: false
    })

    rl.on('line', async (line) => {
      const trimmed = line.trim()
      if (!trimmed) return
      try {
        const response = await handleMessage(trimmed)
        if (response !== null) {
          outStream.write(JSON.stringify(response) + '\n')
        }
      } catch (err) {
        console.error('Fatal MCP message handling error:', err)
      }
    })

    rl.on('close', () => {
      process.exit(0)
    })
  }

  return {
    handleMessage,
    callTool,
    readResource,
    getPrompt,
    tools: MCP_TOOLS,
    resources: MCP_RESOURCES,
    prompts: MCP_PROMPTS,
    start
  }
}

// ── CLI launch ────────────────────────────────────────────────────────────────

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = parseArgs(process.argv.slice(2))
  const server = createMcpServer({ defaultWorkingDir: args.dir ? resolve(args.dir) : process.cwd() })
  server.start()
}
